# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specie',
            name='tax_clasification',
        ),
        migrations.AddField(
            model_name='specie',
            name='classEspecie',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='specie',
            name='family',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='specie',
            name='genus',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='specie',
            name='kingdom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='specie',
            name='order',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='specie',
            name='phylum',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='specie',
            name='species',
            field=models.CharField(default='', max_length=100),
        ),
    ]
