# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0002_auto_20170206_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='specie',
            name='imageFile',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='specie',
            name='large_desc',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='specie',
            name='scientific_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='specie',
            name='short_desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='specie',
            name='tax_clasification',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='imageFile',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
