# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0003_auto_20170215_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='specie',
            name='category_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='especies.Country', verbose_name='Seleccion de Pais'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre de Ciudad'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=200, null=True, verbose_name='Codigo de Pais'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre de Pais'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='especies.Category'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city_name',
            field=models.CharField(default='Bogota', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country_name',
            field=models.CharField(default='Colombia', max_length=100, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default='', max_length=1000, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='imageFile',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Imagen'),
        ),
    ]
