# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0004_auto_20170215_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='specie',
            options={'verbose_name_plural': 'Especimenes'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='specie',
            name='category_name',
        ),
        migrations.AlterField(
            model_name='specie',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='especies.Category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='classEspecie',
            field=models.CharField(default='', max_length=100, verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='family',
            field=models.CharField(default='', max_length=100, verbose_name='Familia'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='genus',
            field=models.CharField(default='', max_length=100, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='imageFile',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='kingdom',
            field=models.CharField(default='', max_length=100, verbose_name='Reino'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='large_desc',
            field=models.TextField(default='', max_length=2000, verbose_name='Descripcion Larga'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='order',
            field=models.CharField(default='', max_length=100, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='phylum',
            field=models.CharField(default='', max_length=100, verbose_name='Filo'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='scientific_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre Comun'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='short_desc',
            field=models.CharField(default='', max_length=200, verbose_name='Descripcion Corta'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='species',
            field=models.CharField(default='', max_length=100, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city_name',
            field=models.CharField(default='Bogota', editable=False, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country_name',
            field=models.CharField(default='Colombia', editable=False, max_length=100, verbose_name='Pais'),
        ),
    ]
