# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0006_auto_20170215_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specie',
            options={'verbose_name': 'Especie', 'verbose_name_plural': 'Especies'},
        ),
        migrations.RemoveField(
            model_name='specie',
            name='scientific_name',
        ),
        migrations.AlterField(
            model_name='specie',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre Comun'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='species',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre Cientifico'),
        ),
    ]
